dataset: repogle_k562_essential_raw
evaluation_targets:
- - k562
  - RPL15
- - k562
  - U2AF1
- - k562
  - RPL4
- - k562
  - RPL7
- - k562
  - RNF113A
- - k562
  - TRRAP
- - k562
  - RPL13
- - k562
  - RPS3
- - k562
  - DDX18
- - k562
  - RPL27A
- - k562
  - SNRPD3
- - k562
  - DNTTIP2
- - k562
  - PHB
- - k562
  - WDR36
- - k562
  - TSR2
- - k562
  - RPL10
- - k562
  - XAB2
- - k562
  - EIF3A
- - k562
  - LSM2
- - k562
  - PCF11
name: rs_accP_k562_ood_ss:ns_20_2_most_pert_0.1-eval_0
