dataset: satija_IFNB_raw
evaluation_targets:
- - A549
  - HERC5
- - A549
  - IFNAR1
- - A549
  - CEBPB
- - A549
  - SP100
- - A549
  - DTX3L
- - A549
  - ADAR
- - A549
  - ID1
- - A549
  - NFKB1
- - A549
  - CRKL
- - A549
  - MYC
name: rs-across-cells-ood-split-ss:10_eval_A549
