dataset: essential_gene_knockouts_raw
evaluation_targets:
- - hepg2
  - ALDOA
- - hepg2
  - FXN
- - hepg2
  - SPC25
- - hepg2
  - ZNF658
- - hepg2
  - TUFM
- - hepg2
  - PFDN2
- - hepg2
  - POLR3H
- - hepg2
  - LAMTOR3
- - hepg2
  - ZC3H13
- - hepg2
  - C1QBP
- - hepg2
  - ZNF676
- - hepg2
  - NDUFAF3
- - hepg2
  - HSPA5
- - hepg2
  - POLL
- - hepg2
  - SCFD1
- - hepg2
  - EEF2
- - hepg2
  - EIF2B2
- - hepg2
  - PPP1CB
- - hepg2
  - HUS1
- - hepg2
  - COASY
- - hepg2
  - SEC61B
- - hepg2
  - SRP14
- - hepg2
  - UMPS
- - hepg2
  - UBE2M
- - hepg2
  - NBPF12
- - hepg2
  - AQP7
- - hepg2
  - YRDC
- - hepg2
  - ESPN
- - hepg2
  - NAPG
- - hepg2
  - MRPS5
- - hepg2
  - OR2T5
- - hepg2
  - PAXBP1
- - hepg2
  - MRPL17
- - hepg2
  - INO80C
- - hepg2
  - UNC45A
- - hepg2
  - JAZF1
- - hepg2
  - MAK16
- - hepg2
  - EXOC1
- - hepg2
  - ZNF720
- - hepg2
  - URM1
name: rs-across-perts-ood-split-ss:40_eval_hepg2
