dataset: essential_gene_knockouts_raw
evaluation_targets:
- - jurkat
  - ALDOA
- - jurkat
  - FXN
- - jurkat
  - SPC25
- - jurkat
  - ZNF658
- - jurkat
  - TUFM
- - jurkat
  - PFDN2
- - jurkat
  - POLR3H
- - jurkat
  - LAMTOR3
- - jurkat
  - ZC3H13
- - jurkat
  - C1QBP
- - jurkat
  - ZNF676
- - jurkat
  - NDUFAF3
- - jurkat
  - HSPA5
- - jurkat
  - POLL
- - jurkat
  - SCFD1
- - jurkat
  - EEF2
- - jurkat
  - EIF2B2
- - jurkat
  - PPP1CB
- - jurkat
  - HUS1
- - jurkat
  - COASY
- - jurkat
  - SEC61B
- - jurkat
  - SRP14
- - jurkat
  - UMPS
- - jurkat
  - UBE2M
- - jurkat
  - NBPF12
- - jurkat
  - AQP7
- - jurkat
  - YRDC
- - jurkat
  - ESPN
- - jurkat
  - NAPG
- - jurkat
  - MRPS5
- - jurkat
  - OR2T5
- - jurkat
  - PAXBP1
- - jurkat
  - MRPL17
- - jurkat
  - INO80C
- - jurkat
  - UNC45A
- - jurkat
  - JAZF1
- - jurkat
  - MAK16
- - jurkat
  - EXOC1
- - jurkat
  - ZNF720
- - jurkat
  - URM1
name: rs-across-perts-ood-split-ss:40_eval_jurkat
