dataset: essential_gene_knockouts_raw
evaluation_targets:
- - k562
  - RPL13
- - k562
  - DDX24
- - k562
  - RPL23A
- - k562
  - NRDE2
- - k562
  - FBL
- - k562
  - CSE1L
- - k562
  - SPC25
- - k562
  - RPS18
- - k562
  - RPL8
- - k562
  - GTF2H1
- - k562
  - RPS19
- - k562
  - MAX
- - k562
  - SUPT6H
- - k562
  - PSMC4
- - k562
  - MED10
- - k562
  - NAA38
- - k562
  - XPO1
- - k562
  - DNTTIP2
- - k562
  - RPL10
- - k562
  - DDX18
name: rs_accP_k562_ood_ss:ns_20_2_most_pert_0.1-eval_0
