dataset: essential_gene_knockouts_raw
evaluation_targets:
- - k562
  - ALDOA
- - k562
  - FXN
- - k562
  - SPC25
- - k562
  - ZNF658
- - k562
  - TUFM
- - k562
  - PFDN2
- - k562
  - POLR3H
- - k562
  - LAMTOR3
- - k562
  - ZC3H13
- - k562
  - C1QBP
- - k562
  - ZNF676
- - k562
  - NDUFAF3
- - k562
  - HSPA5
- - k562
  - POLL
- - k562
  - SCFD1
- - k562
  - EEF2
- - k562
  - EIF2B2
- - k562
  - PPP1CB
- - k562
  - HUS1
- - k562
  - COASY
- - k562
  - SEC61B
- - k562
  - SRP14
- - k562
  - UMPS
- - k562
  - UBE2M
- - k562
  - NBPF12
- - k562
  - AQP7
- - k562
  - YRDC
- - k562
  - ESPN
- - k562
  - NAPG
- - k562
  - MRPS5
- - k562
  - OR2T5
- - k562
  - PAXBP1
- - k562
  - MRPL17
- - k562
  - INO80C
- - k562
  - UNC45A
- - k562
  - JAZF1
- - k562
  - MAK16
- - k562
  - EXOC1
- - k562
  - ZNF720
- - k562
  - URM1
name: rs-across-perts-ood-split-ss:40_eval_k562
