dataset: essential_gene_knockouts_raw
holdout_cells: []
holdout_perts:
- KRTAP4-7
- DDX3X
- CEBPZ
- CDK2
- NAA10
- NMT1
- ATR
- PPA1
- ANKRD17
- ATP5ME
- GPS2
- SRPRB
- SNRPE
- ATL2
- PSMD6
- POU5F1B
- EEFSEC
- HSPH1
- BUB3
- RFT1
mode: ood
name: split_9_ood_ss:ns-20:10
