dataset: essential_gene_knockouts_raw
holdout_cells: []
holdout_perts:
- DDX3X
- NAA10
- PSMD6
- POU5F1B
- ATL2
- SRPRB
- BUB3
- ATP5ME
- CEBPZ
- GPS2
- EEFSEC
- CDK2
- RFT1
- PPA1
- ATR
- ANKRD17
- NMT1
- KRTAP4-7
- SNRPE
- HSPH1
mode: ood
name: split_3_ood_ss:ns-20:10
