dataset: satija_IFNB_raw
evaluation_targets:
- - MCF7
  - HERC5
- - MCF7
  - IFNAR1
- - MCF7
  - CEBPB
- - MCF7
  - SP100
- - MCF7
  - DTX3L
- - MCF7
  - ADAR
- - MCF7
  - ID1
- - MCF7
  - NFKB1
- - MCF7
  - CRKL
- - MCF7
  - MYC
name: rs-across-cells-ood-split-ss:10_eval_MCF7
