name: cinemaot_default
model_type: cinemaot
pert_key: "perturbation"  
control: "No stimulation"  
thres: 0.5
smoothness: 1e-5
eps: 1e-3
solver: "Sinkhorn"
training_epochs: 1  # Not used
batch_size: 1000    # Not used 
seed: 1234
