dataset: repogle_k562_essential_raw
holdout_cells: []
holdout_perts:
- MED30
- LSM6
- PHB
- RPL23
- RPS3
- CDC73
- RPS12
- CHMP3
- RPL36
- PRPF3
- GAB2
- RPS4X
- XPO1
- SON
- NUP54
- DDX47
- SNRPE
- SRRT
- RIOK1
- RPS9
mode: ood
name: rs_accP_k562_ood_ss:ns_20_2_most_pert_0.1-split_1
