dataset: essential_gene_knockouts_raw
evaluation_targets:
- - rpe1
  - ALDOA
- - rpe1
  - FXN
- - rpe1
  - SPC25
- - rpe1
  - ZNF658
- - rpe1
  - TUFM
- - rpe1
  - PFDN2
- - rpe1
  - POLR3H
- - rpe1
  - LAMTOR3
- - rpe1
  - ZC3H13
- - rpe1
  - C1QBP
- - rpe1
  - ZNF676
- - rpe1
  - NDUFAF3
- - rpe1
  - HSPA5
- - rpe1
  - POLL
- - rpe1
  - SCFD1
- - rpe1
  - EEF2
- - rpe1
  - EIF2B2
- - rpe1
  - PPP1CB
- - rpe1
  - HUS1
- - rpe1
  - COASY
- - rpe1
  - SEC61B
- - rpe1
  - SRP14
- - rpe1
  - UMPS
- - rpe1
  - UBE2M
- - rpe1
  - NBPF12
- - rpe1
  - AQP7
- - rpe1
  - YRDC
- - rpe1
  - ESPN
- - rpe1
  - NAPG
- - rpe1
  - MRPS5
- - rpe1
  - OR2T5
- - rpe1
  - PAXBP1
- - rpe1
  - MRPL17
- - rpe1
  - INO80C
- - rpe1
  - UNC45A
- - rpe1
  - JAZF1
- - rpe1
  - MAK16
- - rpe1
  - EXOC1
- - rpe1
  - ZNF720
- - rpe1
  - URM1
name: rs-across-perts-ood-split-ss:40_eval_rpe1
