HVG: false
cell_embeddings: []
cell_key: cell_type
control: non-targeting
count_normalized: false
description: Adamson dataset, pulled from the GEARS code
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/adamson
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/adamson/perturb_processed.h5ad
pert_embeddings: []
pert_key: gene
precomputed_DEGs: false
var_names_key: null
