HVG: false
cell_embeddings: []
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/FrangiehIzar2021/protein/
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/FrangiehIzar2021/protein/FrangiehIzar2021_protein.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
synthetic_versions: []
var_names_key: protein
