HVG: false
cell_embeddings: []
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/GasperiniShendure2019/lowMOI
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/GasperiniShendure2019/lowMOI/GasperiniShendure2019_lowMOI.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
synthetic_versions: []
var_names_key: gene_symbol
