HVG: false
cell_embeddings: []
cell_key: cell_line
control: control
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/PapalexiSatija2021/RNA
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/PapalexiSatija2021/RNA/PapalexiSatija2021_eccite_RNA.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
synthetic_versions: []
var_names_key: gene_symbol
