HVG: false
cell_embeddings: []
cell_key: cell_type
control: control
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/ReplogleWeissman2022/rpe1
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/ReplogleWeissman2022/rpe1/ReplogleWeissman2022_rpe1.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
synthetic_versions: []
var_names_key: gene_name
