HVG: false
cell_embeddings: []
cell_key: cell_line
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/ReplogleWeissman2022/K562_essential
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/ReplogleWeissman2022/K562_essential/ReplogleWeissman2022_K562_essential.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
synthetic_versions: []
var_names_key: null
