HVG: false
cell_embeddings: []
cell_key: celltype
control: non-targeting
count_normalized: false
description: Downloaded from scPerturb website
folder_path: /orcd/data/omarabu/001/Omnicell_datasets/SrivatsanTrapnell2020/sciplex2
gene_embeddings: []
log1p_transformed: false
path: /orcd/data/omarabu/001/Omnicell_datasets/SrivatsanTrapnell2020/sciplex2/SrivatsanTrapnell2020_sciplex2.h5ad
pert_embeddings: []
pert_key: perturbation
precomputed_DEGs: false
synthetic_versions: []
var_names_key: null
